
export DOTFILE_DIR=$(dirname $(dirname $(dirname "$BASH_SOURCE")))

. "${DOTFILE_DIR}"/configs/bash/shell_env

if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook bash)"
fi

if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init bash)"
fi
